//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace PhonebookImportServer.PhonebookModel
{
    #region Kontexty
    
    /// <summary>
    /// Není k dispozici žádná dokumentace metadat.
    /// </summary>
    public partial class Phonebook : ObjectContext
    {
        #region Konstruktory
    
        /// <summary>
        /// Inicializuje nový objekt Phonebook pomocí řetězce připojení v oddílu Phonebook konfiguračního souboru aplikace.
        /// </summary>
        public Phonebook() : base("name=Phonebook", "Phonebook")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializace nového objektu Phonebook
        /// </summary>
        public Phonebook(string connectionString) : base(connectionString, "Phonebook")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializace nového objektu Phonebook
        /// </summary>
        public Phonebook(EntityConnection connection) : base(connection, "Phonebook")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Částečné metody
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Vlastnosti ObjectSet
    
        /// <summary>
        /// Není k dispozici žádná dokumentace metadat.
        /// </summary>
        public ObjectSet<phonebook> phonebook
        {
            get
            {
                if ((_phonebook == null))
                {
                    _phonebook = base.CreateObjectSet<phonebook>("phonebook");
                }
                return _phonebook;
            }
        }
        private ObjectSet<phonebook> _phonebook;

        #endregion

        #region Metody AddTo
    
        /// <summary>
        /// Zastaralá metoda pro přidání nového objektu do phonebook EntitySet. Zvažte použití metody .Add přidružené vlastnosti ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTophonebook(phonebook phonebook)
        {
            base.AddObject("phonebook", phonebook);
        }

        #endregion

    }

    #endregion

    #region Entity
    
    /// <summary>
    /// Není k dispozici žádná dokumentace metadat.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PhonebookImportServer.PhonebookModel", Name="phonebook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class phonebook : EntityObject
    {
        #region Výrobní metoda
    
        /// <summary>
        /// Vytvoření nového objektu phonebook
        /// </summary>
        /// <param name="id">Počáteční hodnota vlastnosti id</param>
        /// <param name="number">Počáteční hodnota vlastnosti number</param>
        /// <param name="public">Počáteční hodnota vlastnosti public</param>
        /// <param name="vip">Počáteční hodnota vlastnosti vip</param>
        public static phonebook Createphonebook(global::System.Int32 id, global::System.String number, global::System.Boolean @public, global::System.Boolean vip)
        {
            phonebook phonebook = new phonebook();
            phonebook.id = id;
            phonebook.number = number;
            phonebook.@public = @public;
            phonebook.vip = vip;
            return phonebook;
        }

        #endregion

        #region Primitivní vlastnosti
    
        /// <summary>
        /// Není k dispozici žádná dokumentace metadat.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Není k dispozici žádná dokumentace metadat.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sys_country_id
        {
            get
            {
                return _sys_country_id;
            }
            set
            {
                Onsys_country_idChanging(value);
                ReportPropertyChanging("sys_country_id");
                _sys_country_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sys_country_id");
                Onsys_country_idChanged();
            }
        }
        private Nullable<global::System.Int32> _sys_country_id;
        partial void Onsys_country_idChanging(Nullable<global::System.Int32> value);
        partial void Onsys_country_idChanged();
    
        /// <summary>
        /// Není k dispozici žádná dokumentace metadat.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String number
        {
            get
            {
                return _number;
            }
            set
            {
                OnnumberChanging(value);
                ReportPropertyChanging("number");
                _number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("number");
                OnnumberChanged();
            }
        }
        private global::System.String _number;
        partial void OnnumberChanging(global::System.String value);
        partial void OnnumberChanged();
    
        /// <summary>
        /// Není k dispozici žádná dokumentace metadat.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// Není k dispozici žádná dokumentace metadat.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String company
        {
            get
            {
                return _company;
            }
            set
            {
                OncompanyChanging(value);
                ReportPropertyChanging("company");
                _company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("company");
                OncompanyChanged();
            }
        }
        private global::System.String _company;
        partial void OncompanyChanging(global::System.String value);
        partial void OncompanyChanged();
    
        /// <summary>
        /// Není k dispozici žádná dokumentace metadat.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone_type
        {
            get
            {
                return _phone_type;
            }
            set
            {
                Onphone_typeChanging(value);
                ReportPropertyChanging("phone_type");
                _phone_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone_type");
                Onphone_typeChanged();
            }
        }
        private global::System.String _phone_type;
        partial void Onphone_typeChanging(global::System.String value);
        partial void Onphone_typeChanged();
    
        /// <summary>
        /// Není k dispozici žádná dokumentace metadat.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean @public
        {
            get
            {
                return _public;
            }
            set
            {
                OnpublicChanging(value);
                ReportPropertyChanging("public");
                _public = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("public");
                OnpublicChanged();
            }
        }
        private global::System.Boolean _public;
        partial void OnpublicChanging(global::System.Boolean value);
        partial void OnpublicChanged();
    
        /// <summary>
        /// Není k dispozici žádná dokumentace metadat.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean vip
        {
            get
            {
                return _vip;
            }
            set
            {
                OnvipChanging(value);
                ReportPropertyChanging("vip");
                _vip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vip");
                OnvipChanged();
            }
        }
        private global::System.Boolean _vip;
        partial void OnvipChanging(global::System.Boolean value);
        partial void OnvipChanged();

        #endregion

    
    }

    #endregion

    
}
