//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonebookImportClient.PhobeboookImportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhobeboookImportService.IPhonebookImportService")]
    public interface IPhonebookImportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhonebookImportService/GetAppName", ReplyAction="http://tempuri.org/IPhonebookImportService/GetAppNameResponse")]
        string GetAppName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhonebookImportService/GetAppName", ReplyAction="http://tempuri.org/IPhonebookImportService/GetAppNameResponse")]
        System.Threading.Tasks.Task<string> GetAppNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhonebookImportService/ImportContacts", ReplyAction="http://tempuri.org/IPhonebookImportService/ImportContactsResponse")]
        bool ImportContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhonebookImportService/ImportContacts", ReplyAction="http://tempuri.org/IPhonebookImportService/ImportContactsResponse")]
        System.Threading.Tasks.Task<bool> ImportContactsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhonebookImportServiceChannel : PhonebookImportClient.PhobeboookImportService.IPhonebookImportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhonebookImportServiceClient : System.ServiceModel.ClientBase<PhonebookImportClient.PhobeboookImportService.IPhonebookImportService>, PhonebookImportClient.PhobeboookImportService.IPhonebookImportService {
        
        public PhonebookImportServiceClient() {
        }
        
        public PhonebookImportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhonebookImportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhonebookImportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhonebookImportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAppName() {
            return base.Channel.GetAppName();
        }
        
        public System.Threading.Tasks.Task<string> GetAppNameAsync() {
            return base.Channel.GetAppNameAsync();
        }
        
        public bool ImportContacts() {
            return base.Channel.ImportContacts();
        }
        
        public System.Threading.Tasks.Task<bool> ImportContactsAsync() {
            return base.Channel.ImportContactsAsync();
        }
    }
}
